### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by Jaanav123** [axivl/whitelistbot#4]
So what about the file and the roblox hub?

**Comment by Gamer-kw0yt** [comment]
Exactly!! How is this meant to work if we don’t have any hub?

**Comment by axivl** [comment]
As it says in the README.md (aswell as the name of the repository, and as I have stated many times before) this is a whitelisting bot and a whitelisting bot only. This isn't simply code that you can expect it to work out of the box as a full system, this is a basic system for whitelisting products only. If you want to add this functionality yourself then go ahead, as if you are working with any sort of code you should know how to code yourself. I have made a backend system for whitelisting, if you want it to work with a hub then you are expected to make your own hub. If you can't be bothered to do this and just expect me to do it at your command, go buy myPod or Kireko or some other similar service.
